Repository FA24SE112-Tech-Gadgets/TechGadgetsBackend, pull requests merged in 2024-10, with the labels that each got.

#1 Update Dev
  WebApi/Data/Entities/User.cs
  WebApi/Data/Migrations/20241005040753_InitialCreate.Designer.cs
  WebApi/Data/Migrations/20241005040753_InitialCreate.cs
  WebApi/Data/Migrations/AppDbContextModelSnapshot.cs
Labels: dev update

#2 Prod Migration
  WebApi/Data/Entities/User.cs
  WebApi/Data/Migrations/20241005040753_InitialCreate.Designer.cs
  WebApi/Data/Migrations/20241005040753_InitialCreate.cs
  WebApi/Data/Migrations/AppDbContextModelSnapshot.cs
Labels: prod migration

#3 Scrape data service
  WebApi/Common/Settings/ScrapeDataSettings.cs
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Features/TestScrape/GetScrapeGadget.cs
  WebApi/Features/TestScrape/Mappers/TestMapper.cs
  WebApi/Features/TestScrape/Models/BrandResponseTest.cs
  WebApi/Features/TestScrape/Models/CategoryResponseTest.cs
  WebApi/Features/TestScrape/Models/GadgetDescriptionResponseTest.cs
  WebApi/Features/TestScrape/Models/GadgetImageResponseTest.cs
  WebApi/Features/TestScrape/Models/GadgetResponseTest.cs
  WebApi/Features/TestScrape/Models/SellerResponseTest.cs
  WebApi/Features/TestScrape/Models/ShopResponseTest.cs
  WebApi/Features/TestScrape/Models/SpecificationKeyResponseTest.cs
  WebApi/Features/TestScrape/Models/SpecificationResponseTest.cs
  WebApi/Features/TestScrape/Models/SpecificationValueResponseTest.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/Background/GadgetScrapeData/Models/GadgetFPTShopItemJsonResponse.cs
  WebApi/Services/Background/GadgetScrapeData/Models/GadgetItemJsonResponse.cs
  WebApi/Services/ScrapeData/ScrapeFPTShopDataService.cs
  WebApi/Services/ScrapeData/ScrapeTGDDDataService.cs
  WebApi/WebApi.csproj
  WebApi/appsettings.Local.json
Labels: enhancement

#4 Update Dev
  WebApi/Common/Settings/ScrapeDataSettings.cs
  WebApi/Data/Configurations/CategoryBrandConfiguration.cs
  WebApi/Data/Migrations/20241005132243_InitialCreate.Designer.cs
  WebApi/Data/Migrations/20241005132243_InitialCreate.cs
  WebApi/Data/Migrations/AppDbContextModelSnapshot.cs
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Features/TestScrape/GetScrapeGadget.cs
  WebApi/Features/TestScrape/Mappers/TestMapper.cs
  WebApi/Features/TestScrape/Models/BrandResponseTest.cs
  WebApi/Features/TestScrape/Models/CategoryResponseTest.cs
  WebApi/Features/TestScrape/Models/GadgetDescriptionResponseTest.cs
  WebApi/Features/TestScrape/Models/GadgetImageResponseTest.cs
  WebApi/Features/TestScrape/Models/GadgetResponseTest.cs
  WebApi/Features/TestScrape/Models/SellerResponseTest.cs
  WebApi/Features/TestScrape/Models/ShopResponseTest.cs
  WebApi/Features/TestScrape/Models/SpecificationKeyResponseTest.cs
  WebApi/Features/TestScrape/Models/SpecificationResponseTest.cs
  WebApi/Features/TestScrape/Models/SpecificationValueResponseTest.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/Background/GadgetScrapeData/Models/GadgetFPTShopItemJsonResponse.cs
  WebApi/Services/Background/GadgetScrapeData/Models/GadgetItemJsonResponse.cs
  WebApi/Services/ScrapeData/ScrapeFPTShopDataService.cs
  WebApi/Services/ScrapeData/ScrapeTGDDDataService.cs
  WebApi/WebApi.csproj
  WebApi/appsettings.Local.json
Labels: dev update

#6 Update Dev
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/ScrapeData/ScrapeFPTShopDataService.cs
  WebApi/Services/ScrapeData/ScrapeTGDDDataService.cs
Labels: dev update

#7 Update Dev
  .github/workflows/deploy-dev.yml
  WebApi/appsettings.Development.json
Labels: dev update

#8 Migrate to prod
  .github/workflows/deploy-dev.yml
  WebApi/Common/Settings/ScrapeDataSettings.cs
  WebApi/Data/Configurations/CategoryBrandConfiguration.cs
  WebApi/Data/Migrations/20241005132243_InitialCreate.Designer.cs
  WebApi/Data/Migrations/20241005132243_InitialCreate.cs
  WebApi/Data/Migrations/AppDbContextModelSnapshot.cs
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Features/TestScrape/GetScrapeGadget.cs
  WebApi/Features/TestScrape/Mappers/TestMapper.cs
  WebApi/Features/TestScrape/Models/BrandResponseTest.cs
  WebApi/Features/TestScrape/Models/CategoryResponseTest.cs
  WebApi/Features/TestScrape/Models/GadgetDescriptionResponseTest.cs
  WebApi/Features/TestScrape/Models/GadgetImageResponseTest.cs
  WebApi/Features/TestScrape/Models/GadgetResponseTest.cs
  WebApi/Features/TestScrape/Models/SellerResponseTest.cs
  WebApi/Features/TestScrape/Models/ShopResponseTest.cs
  WebApi/Features/TestScrape/Models/SpecificationKeyResponseTest.cs
  WebApi/Features/TestScrape/Models/SpecificationResponseTest.cs
  WebApi/Features/TestScrape/Models/SpecificationValueResponseTest.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/Background/GadgetScrapeData/Models/GadgetFPTShopItemJsonResponse.cs
  WebApi/Services/Background/GadgetScrapeData/Models/GadgetItemJsonResponse.cs
  WebApi/Services/ScrapeData/ScrapeFPTShopDataService.cs
  WebApi/Services/ScrapeData/ScrapeTGDDDataService.cs
  WebApi/WebApi.csproj
  WebApi/appsettings.Development.json
  WebApi/appsettings.Local.json
Labels: prod migration

#9 Update Dev
  WebApi/Dockerfile
  WebApi/Services/ScrapeData/ScrapeFPTShopDataService.cs
  WebApi/Services/ScrapeData/ScrapeTGDDDataService.cs
Labels: dev update

#10 Migrate to Prod
  WebApi/Dockerfile
  WebApi/Services/ScrapeData/ScrapeFPTShopDataService.cs
  WebApi/Services/ScrapeData/ScrapeTGDDDataService.cs
Labels: prod migration

#11 Fix time bg task
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
Labels: enhancement

#12 Update Dev
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
Labels: dev update

#13 Migrate to prod
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
Labels: prod migration

#14 fix api for testing
  WebApi/Features/TestScrape/GetScrapeGadget.cs
  WebApi/Features/TestScrape/Mappers/TestMapper.cs
Labels: enhancement

#15 Update Dev
  WebApi/Features/TestScrape/GetScrapeGadget.cs
  WebApi/Features/TestScrape/Mappers/TestMapper.cs
Labels: dev update

#16 Migrate to prod
  WebApi/Features/TestScrape/GetScrapeGadget.cs
  WebApi/Features/TestScrape/Mappers/TestMapper.cs
Labels: prod migration

#17 Update Dev
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/ScrapeData/ScrapeFPTShopDataService.cs
  WebApi/Services/ScrapeData/ScrapeTGDDDataService.cs
Labels: dev update

#18 Migrate to prod
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/ScrapeData/ScrapeFPTShopDataService.cs
  WebApi/Services/ScrapeData/ScrapeTGDDDataService.cs
Labels: prod migration

#19 Finish map scraped gadget
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/ScrapeData/GadgetParentMapService.cs
Labels: enhancement

#20 Update Dev
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/ScrapeData/GadgetParentMapService.cs
Labels: dev update

#22 Update Dev
  WebApi/Services/ScrapeData/GadgetParentMapService.cs
Labels: dev update

#21 Migrate to prod
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/ScrapeData/GadgetParentMapService.cs
Labels: prod migration

#23 Update bgTask scrape service
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/ScrapeData/GadgetParentMapService.cs
Labels: enhancement

#25 Seller application
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
  WebApi/Features/SellerApplications/Mappers/SellerApplicationMapper.cs
  WebApi/Features/SellerApplications/RejectSellerApplication.cs
  WebApi/Features/Users/GetCurrentUser.cs
Labels: enhancement

#26 Update Dev
  WebApi/Common/Settings/EmbeddingServerSettings.cs
  WebApi/Data/AppDbContext.cs
  WebApi/Data/Configurations/SellerConfiguration.cs
  WebApi/Data/Entities/Gadget.cs
  WebApi/Data/Entities/Seller.cs
  WebApi/Data/Entities/SellerApplication.cs
  WebApi/Data/Migrations/20241007124852_InitialCreate.Designer.cs
  WebApi/Data/Migrations/20241007124852_InitialCreate.cs
  WebApi/Data/Migrations/AppDbContextModelSnapshot.cs
  WebApi/Extensions/DbConnectionExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
  WebApi/Features/SellerApplications/Mappers/SellerApplicationMapper.cs
  WebApi/Features/SellerApplications/RejectSellerApplication.cs
  WebApi/Features/Users/GetCurrentUser.cs
  WebApi/Features/Users/Mappers/SellerMapper.cs
  WebApi/Program.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/Embedding/EmbeddingService.cs
  WebApi/Services/ScrapeData/GadgetParentMapService.cs
  WebApi/Services/ScrapeData/ScrapeFPTShopDataService.cs
  WebApi/Services/ScrapeData/ScrapeTGDDDataService.cs
  WebApi/WebApi.csproj
  WebApi/appsettings.Local.json
Labels: dev update

#27 Migrate to prod
  WebApi/Common/Settings/EmbeddingServerSettings.cs
  WebApi/Data/AppDbContext.cs
  WebApi/Data/Configurations/SellerConfiguration.cs
  WebApi/Data/Entities/Gadget.cs
  WebApi/Data/Entities/Seller.cs
  WebApi/Data/Entities/SellerApplication.cs
  WebApi/Data/Migrations/20241007124852_InitialCreate.Designer.cs
  WebApi/Data/Migrations/20241007124852_InitialCreate.cs
  WebApi/Data/Migrations/AppDbContextModelSnapshot.cs
  WebApi/Extensions/DbConnectionExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
  WebApi/Features/SellerApplications/Mappers/SellerApplicationMapper.cs
  WebApi/Features/SellerApplications/RejectSellerApplication.cs
  WebApi/Features/Users/GetCurrentUser.cs
  WebApi/Features/Users/Mappers/SellerMapper.cs
  WebApi/Program.cs
  WebApi/Services/Background/GadgetScrapeData/GadgetScrapeDataService.cs
  WebApi/Services/Embedding/EmbeddingService.cs
  WebApi/Services/ScrapeData/GadgetParentMapService.cs
  WebApi/Services/ScrapeData/ScrapeFPTShopDataService.cs
  WebApi/Services/ScrapeData/ScrapeTGDDDataService.cs
  WebApi/WebApi.csproj
  WebApi/appsettings.Local.json
Labels: prod migration

#28 Finish get list seller application, seller application detail and get…
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
  WebApi/Features/SellerApplications/GetSellerApplicationById.cs
  WebApi/Features/SellerApplications/GetSellerApplications.cs
  WebApi/Features/SellerApplications/Mappers/SellerApplicationMapper.cs
  WebApi/Features/SellerApplications/Models/BillingMailApplicationResponse.cs
  WebApi/Features/SellerApplications/Models/SellerApplicationDetailResponse.cs
  WebApi/Features/SellerApplications/Models/SellerApplicationItemResponse.cs
  WebApi/Features/Sellers/GetSellerDetail.cs
  WebApi/Features/Sellers/Mappers/SellerMapper.cs
  WebApi/Features/Sellers/Models/BillingMailResponse.cs
  WebApi/Features/Sellers/Models/SellerDetailResponse.cs
  WebApi/Features/Sellers/Models/UserDetailResponse.cs
Labels: enhancement

#29 Update dev
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
  WebApi/Features/SellerApplications/GetSellerApplicationById.cs
  WebApi/Features/SellerApplications/GetSellerApplications.cs
  WebApi/Features/SellerApplications/Mappers/SellerApplicationMapper.cs
  WebApi/Features/SellerApplications/Models/BillingMailApplicationResponse.cs
  WebApi/Features/SellerApplications/Models/SellerApplicationDetailResponse.cs
  WebApi/Features/SellerApplications/Models/SellerApplicationItemResponse.cs
  WebApi/Features/Sellers/GetSellerDetail.cs
  WebApi/Features/Sellers/Mappers/SellerMapper.cs
  WebApi/Features/Sellers/Models/BillingMailResponse.cs
  WebApi/Features/Sellers/Models/SellerDetailResponse.cs
  WebApi/Features/Sellers/Models/UserDetailResponse.cs
Labels: dev update

#30 Migrate to prod
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
  WebApi/Features/SellerApplications/GetSellerApplicationById.cs
  WebApi/Features/SellerApplications/GetSellerApplications.cs
  WebApi/Features/SellerApplications/Mappers/SellerApplicationMapper.cs
  WebApi/Features/SellerApplications/Models/BillingMailApplicationResponse.cs
  WebApi/Features/SellerApplications/Models/SellerApplicationDetailResponse.cs
  WebApi/Features/SellerApplications/Models/SellerApplicationItemResponse.cs
  WebApi/Features/Sellers/GetSellerDetail.cs
  WebApi/Features/Sellers/Mappers/SellerMapper.cs
  WebApi/Features/Sellers/Models/BillingMailResponse.cs
  WebApi/Features/Sellers/Models/SellerDetailResponse.cs
  WebApi/Features/Sellers/Models/UserDetailResponse.cs
Labels: prod migration

#31 fix bug
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
Labels: bug

#32 Update Dev
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
Labels: dev update

#34 fix bug
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
Labels: bug

#35 Update Dev
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
Labels: dev update

#33 Migrate to prod
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
Labels: prod migration

#36 Cart management
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/SignupUser.cs
  WebApi/Features/Carts/GetCustomerCart.cs
  WebApi/Features/Carts/Mappers/CartMapper.cs
  WebApi/Features/Carts/Models/BrandCartResponse.cs
  WebApi/Features/Carts/Models/CartGadgetItemResponse.cs
  WebApi/Features/Carts/Models/CartItemResponse.cs
  WebApi/Features/Carts/Models/CartResponse.cs
  WebApi/Features/Carts/Models/CategoryCartResponse.cs
  WebApi/Features/Carts/Models/SellerCartResponse.cs
  WebApi/Features/Carts/Models/UserCartResponse.cs
Labels: enhancement

#37 Change user password
  WebApi/Features/Users/ChangeUserPassword.cs
Labels: enhancement

#38 Forgot user password
  WebApi/Features/Auth/ForgotUserPassword.cs
  WebApi/Services/VerifyCode/VerifyCodeService.cs
Labels: enhancement

#39 Gadget history
  WebApi/Features/GadgetHistories/GetGadgetHistories.cs
  WebApi/Features/GadgetHistories/Mappers/GadgetHistoryMapper.cs
  WebApi/Features/GadgetHistories/Models/BrandGadgetHistoryResponse.cs
  WebApi/Features/GadgetHistories/Models/CategoryGadgetHistoryResponse.cs
  WebApi/Features/GadgetHistories/Models/GadgetHistoryItemResponse.cs
  WebApi/Features/GadgetHistories/Models/GadgetHistoryResponse.cs
  WebApi/Features/GadgetHistories/Models/SellerGadgetHistoryResponse.cs
  WebApi/Features/GadgetHistories/Models/UserGadgetHistoryResponse.cs
Labels: enhancement

#40 Favorite gadget
  WebApi/Features/FavoriteGadgets/CustomerCreateDeleteFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/DeleteCustomerFavoriteGadgets.cs
  WebApi/Features/FavoriteGadgets/GetCustomerFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/Mappers/FavoriteGadgetMapper.cs
  WebApi/Features/FavoriteGadgets/Models/BrandFavoriteGadgetResponse.cs
  WebApi/Features/FavoriteGadgets/Models/CategoryFavoriteGadgetResponse.cs
  WebApi/Features/FavoriteGadgets/Models/FavoriteGadgetItemResponse.cs
  WebApi/Features/FavoriteGadgets/Models/FavoriteGadgetResponse.cs
  WebApi/Features/FavoriteGadgets/Models/SellerFavoriteGadgetResponse.cs
  WebApi/Features/FavoriteGadgets/Models/UserFavoriteGadgetResponse.cs
Labels: enhancement

#41 Customers
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
Labels: enhancement

#42 Seller application
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
Labels: enhancement

#43 Crud gadget
  WebApi/Data/Seeds/SpecificationKeySeed.cs
  WebApi/Data/Seeds/SpecificationUnitSeed.cs
  WebApi/Extensions/ApplyMigrationsExtensions.cs
  WebApi/Features/Brands/GetBrands.cs
  WebApi/Features/Brands/GetBrandsByCategory.cs
  WebApi/Features/Brands/Mappers/BrandMapper.cs
  WebApi/Features/Brands/Models/BrandResponse.cs
  WebApi/Features/Categories/GetCategories.cs
  WebApi/Features/Categories/Mappers/CategoryMapper.cs
  WebApi/Features/Categories/Models/CategoryResponse.cs
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/GetGadgetById.cs
  WebApi/Features/Gadgets/GetGadgets.cs
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetDescriptionResponse.cs
  WebApi/Features/Gadgets/Models/GadgetDetailResponse.cs
  WebApi/Features/Gadgets/Models/GadgetResponse.cs
  WebApi/Features/Gadgets/Models/SpecificationValueResponse.cs
  WebApi/Features/SpecificationKeys/GetSpecificationKeys.cs
  WebApi/Features/SpecificationKeys/GetSpecificationKeysByCategory.cs
  WebApi/Features/SpecificationKeys/Mappers/SpecificationKeyMapper.cs
  WebApi/Features/SpecificationKeys/Models/SpecificationKeyResponse.cs
  WebApi/Features/SpecificationKeys/Models/SpecificationUnitResponse.cs
  WebApi/Services/Auth/CurrentUserService.cs
Labels: enhancement

#45 Cart management
  WebApi/Features/Carts/DeleteCartItemBySellerId.cs
  WebApi/Features/Carts/DeleteCustomerCartItems.cs
  WebApi/Features/Carts/GetCartItemsBySellerId.cs
  WebApi/Features/Carts/GetCustomerCart.cs
  WebApi/Features/Carts/GetListSellerInCart.cs
  WebApi/Features/Carts/Mappers/CartMapper.cs
  WebApi/Features/Carts/Models/CartGadgetItemResponse.cs
  WebApi/Features/Carts/Models/CartItemResponse.cs
  WebApi/Features/Carts/Models/SellerCartResponse.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/FavoriteGadgets/CustomerCreateDeleteFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/GetCustomerFavoriteGadget.cs
  WebApi/Features/GadgetHistories/GetGadgetHistories.cs
Labels: enhancement

#46 Update dev
  WebApi/Features/Carts/DeleteCartItemBySellerId.cs
  WebApi/Features/Carts/DeleteCustomerCartItems.cs
  WebApi/Features/Carts/GetCartItemsBySellerId.cs
  WebApi/Features/Carts/GetCustomerCart.cs
  WebApi/Features/Carts/GetListSellerInCart.cs
  WebApi/Features/Carts/Mappers/CartMapper.cs
  WebApi/Features/Carts/Models/CartGadgetItemResponse.cs
  WebApi/Features/Carts/Models/CartItemResponse.cs
  WebApi/Features/Carts/Models/SellerCartResponse.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/FavoriteGadgets/CustomerCreateDeleteFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/GetCustomerFavoriteGadget.cs
  WebApi/Features/GadgetHistories/GetGadgetHistories.cs
Labels: dev update

#47 Migrate to prod
  WebApi/Features/Carts/DeleteCartItemBySellerId.cs
  WebApi/Features/Carts/DeleteCustomerCartItems.cs
  WebApi/Features/Carts/GetCartItemsBySellerId.cs
  WebApi/Features/Carts/GetCustomerCart.cs
  WebApi/Features/Carts/GetListSellerInCart.cs
  WebApi/Features/Carts/Mappers/CartMapper.cs
  WebApi/Features/Carts/Models/CartGadgetItemResponse.cs
  WebApi/Features/Carts/Models/CartItemResponse.cs
  WebApi/Features/Carts/Models/SellerCartResponse.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/FavoriteGadgets/CustomerCreateDeleteFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/GetCustomerFavoriteGadget.cs
  WebApi/Features/GadgetHistories/GetGadgetHistories.cs
Labels: prod migration

#48 Fix Swagger Description
  WebApi/Features/Carts/GetCartItemsBySellerId.cs
  WebApi/Features/Carts/GetListSellerInCart.cs
Labels: enhancement

#49 Update Dev
  WebApi/Features/Carts/GetCartItemsBySellerId.cs
  WebApi/Features/Carts/GetListSellerInCart.cs
Labels: dev update

#50 Migrate to prod
  WebApi/Features/Carts/GetCartItemsBySellerId.cs
  WebApi/Features/Carts/GetListSellerInCart.cs
Labels: prod migration

#51 Upload Image
  WebApi/Features/Images/UploadImage.cs
Labels: enhancement

#52 Update Dev
  WebApi/Features/Images/UploadImage.cs
Labels: dev update

#53 Upload Multiple Images
  WebApi/Features/Images/UploadImages.cs
Labels: enhancement

#54 Update Dev
  WebApi/Features/Images/UploadImages.cs
Labels: dev update

#55 Fix ChangeUserPassword
  WebApi/Features/Users/ChangeUserPassword.cs
  WebApi/Services/Payment/Models/PayOSPayment.cs
  WebApi/Services/Payment/Models/PayOSPaymentRequest.cs
  WebApi/Services/Payment/PayOSPaymentSerivce.cs
Labels: enhancement

#56 Update Dev
  WebApi/Features/Users/ChangeUserPassword.cs
  WebApi/Services/Payment/Models/PayOSPayment.cs
  WebApi/Services/Payment/Models/PayOSPaymentRequest.cs
  WebApi/Services/Payment/PayOSPaymentSerivce.cs
Labels: dev update

#57 Migrate to prod
  WebApi/Features/Images/UploadImage.cs
  WebApi/Features/Images/UploadImages.cs
  WebApi/Features/Users/ChangeUserPassword.cs
  WebApi/Services/Payment/Models/PayOSPayment.cs
  WebApi/Services/Payment/Models/PayOSPaymentRequest.cs
  WebApi/Services/Payment/PayOSPaymentSerivce.cs
Labels: prod migration

#58 update payos webhook
  WebApi/Features/Payments/Models/PaymentResponse.cs
  WebApi/Features/Payments/PayOSPayment.cs
Labels: enhancement

#59 Update Dev
  WebApi/Features/Payments/Models/PaymentResponse.cs
  WebApi/Features/Payments/PayOSPayment.cs
Labels: dev update

#60 Fix tags
  WebApi/Features/Payments/PayOSPayment.cs
Labels: enhancement

#61 Update Dev
  WebApi/Features/Payments/PayOSPayment.cs
Labels: dev update

#62 fix payos configuration
  WebApi/appsettings.Local.json
Labels: enhancement

#63 Update Dev
  WebApi/appsettings.Local.json
Labels: dev update

#64 Migrate to prod
  .github/workflows/deploy-dev.yml
  WebApi/Features/Payments/Models/PaymentResponse.cs
  WebApi/Features/Payments/PayOSPayment.cs
  WebApi/appsettings.Development.json
  WebApi/appsettings.Local.json
Labels: prod migration

#65 Pay os payment service
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Payments/PayOSPayments.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/Features/Wallets/Models/DepositResponse.cs
  WebApi/Services/Payment/Models/PayOSPayment.cs
  WebApi/Services/Payment/PayOSPaymentSerivce.cs
Labels: enhancement

#67 fix
  WebApi/Features/Wallets/CreateWalletDeposit.cs
Labels: enhancement

#68 Update Dev
  WebApi/Features/Wallets/CreateWalletDeposit.cs
Labels: dev update

#69 Fix seller cart response
  WebApi/Features/Carts/Models/SellerCartResponse.cs
  WebApi/Features/Wallets/CancelTransaction.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
Labels: enhancement

#70 Update Dev
  WebApi/Features/Carts/Models/SellerCartResponse.cs
  WebApi/Features/Wallets/CancelTransaction.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
Labels: dev update

#71 Finish PayOS payment service and create order
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Features/OrderDetails/GetListOrderDetails.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/Mappers/OrderMapper.cs
  WebApi/Features/Payments/PayOSPayments.cs
  WebApi/Features/WalletTrackings/CancelTransaction.cs
  WebApi/Features/WalletTrackings/CreateWalletDeposit.cs
  WebApi/Features/WalletTrackings/GetWalletHistories.cs
  WebApi/Features/WalletTrackings/Mappers/WalletTrackingMapper.cs
  WebApi/Features/WalletTrackings/Models/DepositResponse.cs
  WebApi/Features/WalletTrackings/Models/WalletTrackingItemResponse.cs
  WebApi/Services/Background/SellerApplications/RejectSellerApplicationService.cs
  WebApi/Services/Background/WalletTrackings/ExpiredransactionService.cs
  WebApi/Services/Payment/PayOSPaymentSerivce.cs
Labels: enhancement

#72 Order payment function
  WebApi/Features/OrderDetails/GetListOrderDetails.cs
  WebApi/Features/OrderDetails/Mappers/OrderDetailMapper.cs
  WebApi/Features/OrderDetails/Models/CustomerOrderDetailItemResponse.cs
  WebApi/Features/OrderDetails/Models/GadgetInformationOrderDetailResponse.cs
  WebApi/Features/OrderDetails/Models/SellerOrderDetailItemResponse.cs
  WebApi/Features/OrderDetails/Models/SellerOrderDetailResponse.cs
  WebApi/Features/Orders/CreateOrder.cs
Labels: enhancement

#74 Fix cancel transaction note
  WebApi/Features/WalletTrackings/CancelTransaction.cs
Labels: enhancement

#76 Try seed
  WebApi/Data/Seeds/BrandSeed.cs
  WebApi/Data/Seeds/CategoryBrandSeed.cs
  WebApi/Data/Seeds/GadgetDescriptionSeed.cs
  WebApi/Data/Seeds/GadgetImageSeed.cs
  WebApi/Data/Seeds/GadgetSeed.cs
  WebApi/Data/Seeds/SpecificationKeySeed.cs
  WebApi/Data/Seeds/SpecificationUnitSeed.cs
  WebApi/Data/Seeds/SpecificationValueDienThoaiSeed.cs
  WebApi/Data/Seeds/SpecificationValueLaptopSeed.cs
  WebApi/Data/Seeds/SpecificationValueLoaSeed.cs
  WebApi/Data/Seeds/SpecificationValueSeed.cs
  WebApi/Data/Seeds/SpecificationValueTaiNgheSeed.cs
  WebApi/Data/Seeds/UserSeed.cs
  WebApi/Extensions/ApplyMigrationsExtensions.cs
  WebApi/Services/Embedding/EmbeddingService.cs
Labels: enhancement

#77 Update Dev
  WebApi/Data/Seeds/BrandSeed.cs
  WebApi/Data/Seeds/CategoryBrandSeed.cs
  WebApi/Data/Seeds/GadgetDescriptionSeed.cs
  WebApi/Data/Seeds/GadgetImageSeed.cs
  WebApi/Data/Seeds/GadgetSeed.cs
  WebApi/Data/Seeds/SpecificationKeySeed.cs
  WebApi/Data/Seeds/SpecificationUnitSeed.cs
  WebApi/Data/Seeds/SpecificationValueDienThoaiSeed.cs
  WebApi/Data/Seeds/SpecificationValueLaptopSeed.cs
  WebApi/Data/Seeds/SpecificationValueLoaSeed.cs
  WebApi/Data/Seeds/SpecificationValueSeed.cs
  WebApi/Data/Seeds/SpecificationValueTaiNgheSeed.cs
  WebApi/Data/Seeds/UserSeed.cs
  WebApi/Extensions/ApplyMigrationsExtensions.cs
  WebApi/Services/Embedding/EmbeddingService.cs
Labels: dev update

#78 Update Dev
  WebApi/Extensions/ApplyMigrationsExtensions.cs
Labels: dev update

#79 Order payment function
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Features/OrderDetails/CancelOrderDetail.cs
  WebApi/Features/OrderDetails/GetListOrderDetails.cs
  WebApi/Features/OrderDetails/SellerConfirmOrderDetail.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
  WebApi/Services/Background/WalletTrackings/ExpiredTransactionService.cs
Labels: enhancement

#80 Update Dev
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Features/OrderDetails/CancelOrderDetail.cs
  WebApi/Features/OrderDetails/GetListOrderDetails.cs
  WebApi/Features/OrderDetails/SellerConfirmOrderDetail.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
  WebApi/Services/Background/WalletTrackings/ExpiredTransactionService.cs
Labels: bug

#82 Order payment function
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Features/OrderDetails/CancelOrderDetail.cs
  WebApi/Features/OrderDetails/SellerConfirmOrderDetail.cs
  WebApi/Features/Orders/Mappers/OrderMapper.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
Labels: enhancement

#85 Add wallet to get current user api
  WebApi/Features/Users/Mappers/UserMapper.cs
  WebApi/Features/Users/Mappers/WalletMapper.cs
  WebApi/Features/Users/Models/UserResponse.cs
  WebApi/Features/Users/Models/WalletResponse.cs
  WebApi/Features/Wallets/GetUserWallet.cs
Labels: enhancement

#86 Update Dev
  WebApi/Features/Users/Mappers/UserMapper.cs
  WebApi/Features/Users/Mappers/WalletMapper.cs
  WebApi/Features/Users/Models/UserResponse.cs
  WebApi/Features/Users/Models/WalletResponse.cs
  WebApi/Features/Wallets/GetUserWallet.cs
Labels: dev update

#87 Migrate to prod
  WebApi/Features/Users/Mappers/UserMapper.cs
  WebApi/Features/Users/Mappers/WalletMapper.cs
  WebApi/Features/Users/Models/UserResponse.cs
  WebApi/Features/Users/Models/WalletResponse.cs
  WebApi/Features/Wallets/GetUserWallet.cs
Labels: prod migration

#90 update
  WebApi/Features/OrderDetails/GetOrderDetailInDetail.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/WebApi.csproj
Labels: enhancement

#89 Update Dev
  WebApi/Data/Entities/Customer.cs
  WebApi/Data/Entities/Seller.cs
  WebApi/Features/OrderDetails/GetOrderDetailInDetail.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/Features/Wallets/GetUserWallet.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
Labels: dev update

#91 Migrate to prod
  WebApi/Data/Entities/Customer.cs
  WebApi/Data/Entities/Seller.cs
  WebApi/Features/OrderDetails/GetOrderDetailInDetail.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/Features/Wallets/GetUserWallet.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
Labels: prod migration

#92 Momo and VnPay webhook
  WebApi/Features/Payments/Models/MomoWebhookRequest.cs
  WebApi/Features/Payments/Models/VnPayWebhookRequest.cs
  WebApi/Features/Payments/MomoPayment.cs
  WebApi/Features/Payments/VnPayPayment.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/Services/Payment/Models/MomoPayment.cs
  WebApi/Services/Payment/Models/VnPayPayment.cs
  WebApi/Services/Payment/MomoPaymentService.cs
  WebApi/Services/Payment/VnPayPaymentService.cs
  WebApi/appsettings.Local.json
Labels: enhancement

#93 Order payment function
  WebApi/Features/OrderDetails/GetListGadgetInformationsByOrderDetailId.cs
  WebApi/Features/OrderDetails/GetListOrderDetails.cs
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/OrderDetails/Mappers/CustomerInformationMapper.cs
  WebApi/Features/OrderDetails/Mappers/OrderDetailMapper.cs
  WebApi/Features/OrderDetails/Mappers/SellerInformationMapper.cs
  WebApi/Features/OrderDetails/Models/CustomerInfoResponse.cs
  WebApi/Features/OrderDetails/Models/CustomerOrderDetailItemResponse.cs
  WebApi/Features/OrderDetails/Models/OrderDetailResponse.cs
  WebApi/Features/OrderDetails/Models/SellerInfoResponse.cs
  WebApi/Features/OrderDetails/Models/SellerOrderDetailResponse.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/SellerApplications/Models/SellerApplicationDetailResponse.cs
  WebApi/Features/SellerApplications/Models/SellerApplicationItemResponse.cs
Labels: enhancement

#95 Order payment function
  WebApi/Features/OrderDetails/GetListOrderDetails.cs
  WebApi/Features/OrderDetails/Mappers/OrderDetailMapper.cs
  WebApi/Features/OrderDetails/Models/CustomerOrderDetailItemResponse.cs
  WebApi/Features/Orders/CreateOrder.cs
Labels: enhancement

#96 Update Dev
  WebApi/Features/OrderDetails/GetListOrderDetails.cs
  WebApi/Features/OrderDetails/Mappers/OrderDetailMapper.cs
  WebApi/Features/OrderDetails/Models/CustomerOrderDetailItemResponse.cs
  WebApi/Features/Orders/CreateOrder.cs
Labels: dev update

#97 Order payment function
  WebApi/Features/OrderDetails/Mappers/OrderDetailMapper.cs
  WebApi/Features/OrderDetails/Models/GadgetInformationOrderDetailResponse.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
Labels: bug

#98 Update Dev
  WebApi/Features/OrderDetails/Mappers/OrderDetailMapper.cs
  WebApi/Features/OrderDetails/Models/GadgetInformationOrderDetailResponse.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
Labels: dev update

#100 Order payment function
  WebApi/Features/OrderDetails/CancelOrderDetail.cs
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/OrderDetails/Models/OrderDetailResponse.cs
  WebApi/Features/OrderDetails/SellerConfirmOrderDetail.cs
  WebApi/Features/Orders/CreateOrder.cs
Labels: enhancement

#101 Update Dev
  WebApi/Features/OrderDetails/CancelOrderDetail.cs
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/OrderDetails/Models/OrderDetailResponse.cs
  WebApi/Features/OrderDetails/SellerConfirmOrderDetail.cs
  WebApi/Features/Orders/CreateOrder.cs
Labels: dev update

#102 Migrate to prod
  WebApi/Features/OrderDetails/CancelOrderDetail.cs
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/OrderDetails/Models/OrderDetailResponse.cs
  WebApi/Features/OrderDetails/SellerConfirmOrderDetail.cs
  WebApi/Features/Orders/CreateOrder.cs
Labels: prod migration

#103 fix error
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
Labels: bug

#104 Update Dev
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
Labels: enhancement

#105 Migrate to prod
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
Labels: prod migration

#106 Order payment function
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/WalletTrackings/CancelTransaction.cs
Labels: enhancement

#107 Update Dev
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/WalletTrackings/CancelTransaction.cs
Labels: dev update

#108 Migrate to prod
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/WalletTrackings/CancelTransaction.cs
Labels: prod migration

#109 Fix Momo and VnPay
  WebApi/Services/Payment/VnPayPaymentService.cs
Labels: enhancement

#110 Update Dev
  WebApi/Data/Seeds/SellerApplicationSeed.cs
  WebApi/Extensions/ApplyMigrationsExtensions.cs
  WebApi/Features/Payments/MomoPayment.cs
  WebApi/Features/Payments/VnPayPayment.cs
Labels: dev update

#111 Update all user info
  WebApi/Features/Admins/UpdateAdminInfo.cs
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/Managers/UpdateManagerInfo.cs
  WebApi/Features/Sellers/UpdateSellerInfo.cs
Labels: enhancement

#112 Update Dev
  WebApi/Features/Admins/UpdateAdminInfo.cs
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/Managers/UpdateManagerInfo.cs
  WebApi/Features/Sellers/UpdateSellerInfo.cs
Labels: dev update

#117 Update Dev
  WebApi/Features/Reviews/CreateReview.cs
Labels: dev update

#119 Review and reply management
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/OrderDetails/CancelOrderDetail.cs
  WebApi/Features/OrderDetails/GetListGadgetInformationsByOrderDetailId.cs
  WebApi/Features/OrderDetails/GetListOrderDetails.cs
  WebApi/Features/OrderDetails/GetOrderDetailById.cs
  WebApi/Features/OrderDetails/Mappers/OrderDetailMapper.cs
  WebApi/Features/OrderDetails/Models/CustomerOrderDetailItemResponse.cs
  WebApi/Features/OrderDetails/SellerConfirmOrderDetail.cs
  WebApi/Features/Reviews/CreateReview.cs
Labels: bug, enhancement

#122 Review and reply management
  WebApi/Features/FavoriteGadgets/GetCustomerFavoriteGadget.cs
  WebApi/Features/OrderDetails/CancelOrderDetail.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
  WebApi/Features/Reviews/Mappers/CustomerMapper.cs
  WebApi/Features/Reviews/Mappers/ReviewMapper.cs
  WebApi/Features/Reviews/Models/CustomerReviewResponse.cs
  WebApi/Features/Reviews/Models/GadgetReviewResponse.cs
  WebApi/Features/Reviews/Models/ReviewResponse.cs
  WebApi/Features/SellerApplications/GetSellerApplications.cs
  WebApi/Services/Background/OrderDetails/OrderDetailService.cs
  WebApi/Services/Background/SellerApplications/RejectSellerApplicationService.cs
Labels: enhancement

#125 Finish get gadgets by categoryId
  WebApi/Features/OrderDetails/GetGadgetByCategoryId.cs
  WebApi/Features/OrderDetails/Models/GadgetReviewResponse.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
  WebApi/Features/Reviews/Mappers/ReviewMapper.cs
  WebApi/Features/Reviews/Mappers/SellerMapper.cs
  WebApi/Features/Reviews/Mappers/SellerReplyMapper.cs
  WebApi/Features/Reviews/Models/ReviewResponse.cs
  WebApi/Features/Reviews/Models/SellerReplyResponse.cs
  WebApi/Features/Reviews/Models/SellerResponse.cs
Labels: enhancement

#126 Update Dev
  WebApi/Features/OrderDetails/GetGadgetByCategoryId.cs
  WebApi/Features/OrderDetails/Models/GadgetReviewResponse.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
  WebApi/Features/Reviews/Mappers/ReviewMapper.cs
  WebApi/Features/Reviews/Mappers/SellerMapper.cs
  WebApi/Features/Reviews/Mappers/SellerReplyMapper.cs
  WebApi/Features/Reviews/Models/ReviewResponse.cs
  WebApi/Features/Reviews/Models/SellerReplyResponse.cs
  WebApi/Features/Reviews/Models/SellerResponse.cs
Labels: dev update

#127 Migrate to prod
  WebApi/Features/OrderDetails/GetGadgetByCategoryId.cs
  WebApi/Features/OrderDetails/Models/GadgetReviewResponse.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
  WebApi/Features/Reviews/Mappers/ReviewMapper.cs
  WebApi/Features/Reviews/Mappers/SellerMapper.cs
  WebApi/Features/Reviews/Mappers/SellerReplyMapper.cs
  WebApi/Features/Reviews/Models/ReviewResponse.cs
  WebApi/Features/Reviews/Models/SellerReplyResponse.cs
  WebApi/Features/Reviews/Models/SellerResponse.cs
Labels: prod migration

#128 finish get gadget by brandid and fix get by category id
  WebApi/Features/Gadgets/GetGadgetByBrandId.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
Labels: enhancement

#130 Migrate to prod
  WebApi/Features/Gadgets/GetGadgetByBrandId.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
Labels: prod migration

#132 Review and reply management
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/GetGadgetsReviews.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
  WebApi/Features/Reviews/Mappers/GadgetMapper.cs
  WebApi/Features/Reviews/Models/GadgetReviewResponse.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/SellerOrders/GetListSellerOrderItemsBySellerOrderId.cs
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
  WebApi/Features/SellerOrders/GetSellerOrderById.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
  WebApi/Features/SellerOrders/Models/SellerInSellerOrderResponse.cs
  WebApi/Features/SellerOrders/Models/SellerOrderItemInItemResponse.cs
  WebApi/Features/SellerReplies/CreateSellerReply.cs
  WebApi/Features/WalletTrackings/GetWalletHistories.cs
Labels: enhancement

#135 Finish update review and reply. Get gadgets by category and brand
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
  WebApi/Features/Reviews/UpdateReviewByReviewId.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
Labels: enhancement

#136 Update Dev
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
  WebApi/Features/Reviews/UpdateReviewByReviewId.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
Labels: dev update

#137 Migrate to prod
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
  WebApi/Features/Reviews/UpdateReviewByReviewId.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
Labels: prod migration

#138 .
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
Labels: enhancement

#139 Update Dev
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
Labels: dev update

#140 Migrate to prod
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
Labels: prod migration

#142 Update Dev
  WebApi/Features/Payments/MomoPayment.cs
  WebApi/Features/Payments/VnPayPayment.cs
Labels: dev update

#144 Gadgets
  WebApi/Features/GadgetFilters/GetGadgetFilters.cs
  WebApi/Features/GadgetFilters/Mappers/GadgetFilterMapper.cs
  WebApi/Features/GadgetFilters/Models/GadgetFilterResponse.cs
  WebApi/Features/GadgetFilters/Models/GadgetFiltersResponse.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
Labels: enhancement

#145 Update Dev
  WebApi/Features/GadgetFilters/GetGadgetFilters.cs
  WebApi/Features/GadgetFilters/Mappers/GadgetFilterMapper.cs
  WebApi/Features/GadgetFilters/Models/GadgetFilterResponse.cs
  WebApi/Features/GadgetFilters/Models/GadgetFiltersResponse.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
Labels: dev update

#146 Migrate to prod
  WebApi/Features/GadgetFilters/GetGadgetFilters.cs
  WebApi/Features/GadgetFilters/Mappers/GadgetFilterMapper.cs
  WebApi/Features/GadgetFilters/Models/GadgetFilterResponse.cs
  WebApi/Features/GadgetFilters/Models/GadgetFiltersResponse.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
Labels: prod migration

#147 .
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
  WebApi/Features/Orders/CreateOrder.cs
Labels: bug

#148 Update Dev
  WebApi/Features/Gadgets/GetGadgetsByCategoryAndBrand.cs
  WebApi/Features/Orders/CreateOrder.cs
Labels: dev update

#149 fix
  WebApi/Features/Orders/CreateOrder.cs
Labels: enhancement

#150 Update Dev
  WebApi/Features/Orders/CreateOrder.cs
Labels: dev update

#153 Gadgets
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
Labels: enhancement

#154 Update Dev
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
Labels: dev update

#155 Migrate to prod
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
Labels: prod migration

#157 Migrate to Prod
  WebApi/Data/Seeds/GadgetSeed.cs
  WebApi/Extensions/ApplyMigrationsExtensions.cs
Labels: prod migration

#158 Finish Get Hot Gadgets
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/Models/HotGadgetResponse.cs
Labels: enhancement

#159 Update Dev
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/Models/HotGadgetResponse.cs
Labels: dev update

#162 Update Dev
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Orders/CreateOrder.cs
Labels: dev update

#163 Migrate to prod
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Orders/CreateOrder.cs
Labels: prod migration

#164 fix get hot gadgets
  WebApi/Features/Gadgets/GetHotGadgets.cs
Labels: bug

#165 Update Dev
  WebApi/Features/Gadgets/GetHotGadgets.cs
Labels: dev update

#166 Migrate to prod
  WebApi/Features/Gadgets/GetHotGadgets.cs
Labels: prod migration

#167 Orders mangement
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/Orders/Mappers/OrderMapper.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/SellerOrders/GetListSellerOrderItemsBySellerOrderId.cs
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
  WebApi/Features/SellerOrders/GetSellerOrderById.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
  WebApi/Features/SellerOrders/Models/SellerOrderItemInItemResponse.cs
Labels: enhancement

#171 Add field DiscountExpiredDate to response
  WebApi/Features/Carts/Mappers/CartMapper.cs
  WebApi/Features/Carts/Models/CartItemResponse.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetDetailResponse.cs
  WebApi/Features/Gadgets/Models/GadgetResponse.cs
  WebApi/Services/Background/GadgetDiscounts/InactiveGadgetDiscountService.cs
Labels: enhancement

#172 Update Dev
  WebApi/Features/Carts/Mappers/CartMapper.cs
  WebApi/Features/Carts/Models/CartItemResponse.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetDetailResponse.cs
  WebApi/Features/Gadgets/Models/GadgetResponse.cs
  WebApi/Services/Background/GadgetDiscounts/InactiveGadgetDiscountService.cs
Labels: dev update

#174 Finish create gadget discount by gadget id
  WebApi/Features/GadgetDiscounts/CreateGadgetDiscountByGadgetId.cs
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/SellerReplies/CreateSellerReply.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
  WebApi/Features/Sellers/GetSellerDetail.cs
  WebApi/Features/Sellers/UpdateSellerInfo.cs
Labels: enhancement

#175 Finish 80% NotificationHub
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Common/Exceptions/TechGadgetExceptionHandler.cs
  WebApi/Extensions/NotificationHubExtensions.cs
  WebApi/Features/Notifications/Models/TokenRequest.cs
  WebApi/Features/Notifications/NotificationHub.cs
  WebApi/Program.cs
Labels: enhancement

#176 Update Dev
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Common/Exceptions/TechGadgetExceptionHandler.cs
  WebApi/Extensions/NotificationHubExtensions.cs
  WebApi/Features/GadgetDiscounts/CreateGadgetDiscountByGadgetId.cs
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Notifications/Models/TokenRequest.cs
  WebApi/Features/Notifications/NotificationHub.cs
  WebApi/Features/SellerReplies/CreateSellerReply.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
  WebApi/Features/Sellers/GetSellerDetail.cs
  WebApi/Features/Sellers/UpdateSellerInfo.cs
  WebApi/Program.cs
Labels: dev update

#173 Migrate to prod
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Common/Exceptions/TechGadgetExceptionHandler.cs
  WebApi/Extensions/NotificationHubExtensions.cs
  WebApi/Features/Carts/Mappers/CartMapper.cs
  WebApi/Features/Carts/Models/CartItemResponse.cs
  WebApi/Features/GadgetDiscounts/CreateGadgetDiscountByGadgetId.cs
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetDetailResponse.cs
  WebApi/Features/Gadgets/Models/GadgetResponse.cs
  WebApi/Features/Notifications/Models/TokenRequest.cs
  WebApi/Features/Notifications/NotificationHub.cs
  WebApi/Features/SellerReplies/CreateSellerReply.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
  WebApi/Features/Sellers/GetSellerDetail.cs
  WebApi/Features/Sellers/UpdateSellerInfo.cs
  WebApi/Program.cs
  WebApi/Services/Background/GadgetDiscounts/InactiveGadgetDiscountService.cs
Labels: prod migration

#178 test
  WebApi/Features/Notifications/NotificationHub.cs
Labels: dev update

#179 .
  WebApi/Features/Notifications/NotificationHub.cs
Labels: enhancement

#181 Notification hub configuration
  WebApi/Common/Filters/Models/TokenRequest.cs
  WebApi/Common/Filters/RoleRestrictHubRequirement.cs
  WebApi/Extensions/NotificationHubExtensions.cs
  WebApi/Features/Notifications/NotificationHub.cs
  WebApi/Features/Notifications/NotificationTestCurrent.cs
  WebApi/Features/Notifications/NotificationTestGroup.cs
  WebApi/Program.cs
  WebApi/Services/Notification/Models/TokenRequest.cs
  WebApi/Services/Notification/NotificationService.cs
Labels: enhancement

#182 Update Dev
  WebApi/Common/Filters/Models/TokenRequest.cs
  WebApi/Common/Filters/RoleRestrictHubRequirement.cs
  WebApi/Extensions/NotificationHubExtensions.cs
  WebApi/Features/Notifications/NotificationHub.cs
  WebApi/Features/Notifications/NotificationTestCurrent.cs
  WebApi/Features/Notifications/NotificationTestGroup.cs
  WebApi/Program.cs
  WebApi/Services/Notification/Models/TokenRequest.cs
  WebApi/Services/Notification/NotificationService.cs
Labels: dev update

#183 Migrate to prod
  WebApi/Common/Filters/Models/TokenRequest.cs
  WebApi/Common/Filters/RoleRestrictHubRequirement.cs
  WebApi/Extensions/NotificationHubExtensions.cs
  WebApi/Features/Notifications/NotificationHub.cs
  WebApi/Features/Notifications/NotificationTestCurrent.cs
  WebApi/Features/Notifications/NotificationTestGroup.cs
  WebApi/Program.cs
  WebApi/Services/Notification/Models/TokenRequest.cs
  WebApi/Services/Notification/NotificationService.cs
Labels: prod migration

#184 Finish fixing expired discount problem
  WebApi/Features/FavoriteGadgets/GetCustomerFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/Mappers/FavoriteGadgetMapper.cs
  WebApi/Features/FavoriteGadgets/Models/FavoriteGadgetItemResponse.cs
  WebApi/Features/GadgetHistories/GetGadgetHistories.cs
  WebApi/Features/GadgetHistories/Mappers/GadgetHistoryMapper.cs
  WebApi/Features/GadgetHistories/Models/GadgetHistoryItemResponse.cs
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/Orders/Mappers/OrderMapper.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/SellerOrders/GetSellerOrderById.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
  WebApi/Services/Background/GadgetDiscounts/InactiveGadgetDiscountService.cs
Labels: enhancement

#185 Update Dev
  WebApi/Features/FavoriteGadgets/GetCustomerFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/Mappers/FavoriteGadgetMapper.cs
  WebApi/Features/FavoriteGadgets/Models/FavoriteGadgetItemResponse.cs
  WebApi/Features/GadgetHistories/GetGadgetHistories.cs
  WebApi/Features/GadgetHistories/Mappers/GadgetHistoryMapper.cs
  WebApi/Features/GadgetHistories/Models/GadgetHistoryItemResponse.cs
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/Orders/Mappers/OrderMapper.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/SellerOrders/GetSellerOrderById.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
  WebApi/Services/Background/GadgetDiscounts/InactiveGadgetDiscountService.cs
Labels: dev update

#186 Migrate to prod
  WebApi/Features/FavoriteGadgets/GetCustomerFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/Mappers/FavoriteGadgetMapper.cs
  WebApi/Features/FavoriteGadgets/Models/FavoriteGadgetItemResponse.cs
  WebApi/Features/GadgetHistories/GetGadgetHistories.cs
  WebApi/Features/GadgetHistories/Mappers/GadgetHistoryMapper.cs
  WebApi/Features/GadgetHistories/Models/GadgetHistoryItemResponse.cs
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/Orders/Mappers/OrderMapper.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/SellerOrders/GetSellerOrderById.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
  WebApi/Services/Background/GadgetDiscounts/InactiveGadgetDiscountService.cs
Labels: prod migration
