Repository FA24SE112-Tech-Gadgets/TechGadgetsBackend, pull requests merged in 2024-09, with the labels that each got.

#1 configure appsettings.Local.json
  WebApi/appsettings.Local.json
Labels: enhancement

#2 Config json and settings
  WebApi/Common/Settings/GoogleStorageSettings.cs
  WebApi/Common/Settings/JwtSettings.cs
  WebApi/Common/Settings/MailSettings.cs
  WebApi/Common/Settings/MomoSettings.cs
  WebApi/Common/Settings/PayOSSettings.cs
  WebApi/Common/Settings/RabbitMQSettings.cs
  WebApi/Common/Settings/VnPaySettings.cs
  WebApi/DependencyInjections/SettingsDI.cs
  WebApi/appsettings.Local.json
Labels: enhancement

#8 Fix User Verify Bug
  WebApi/Data/AppDbContext.cs
  WebApi/Data/Migrations/20240918085453_AddUserVerify.Designer.cs
  WebApi/Data/Migrations/20240918085453_AddUserVerify.cs
Labels: bug

#10 Authorization
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Common/Exceptions/TechGadgetException.cs
  WebApi/Common/Exceptions/TechGadgetExceptionHandler.cs
  WebApi/Common/Filters/RequestValidationFilter.cs
  WebApi/Common/Settings/MailSettings.cs
  WebApi/Common/Utils/VerificationCodeGenerator.cs
  WebApi/Common/Utils/VerifyCodeGenerator.cs
  WebApi/DependencyInjections/ApplyExpceptionPage.cs
  WebApi/DependencyInjections/ExceptionHandlerDI.cs
  WebApi/DependencyInjections/JsonOptionsDI.cs
  WebApi/DependencyInjections/RouteConfigurationDI.cs
  WebApi/DependencyInjections/ServicesDI.cs
  WebApi/DependencyInjections/SwaggerDI.cs
  WebApi/Features/Auth/GoogleLogin.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/Mappers/GoogleLoginMapper.cs
  WebApi/Features/Auth/Mappers/TokenMapper.cs
  WebApi/Features/Auth/Models/LoginGoogleResponse.cs
  WebApi/Features/Auth/Models/RegisterUserRequest.cs
  WebApi/Features/Auth/Models/TokenResponse.cs
  WebApi/Features/Auth/ResendVerify.cs
  WebApi/Features/Auth/SignupUser.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Users/Models/UserInfo.cs
  WebApi/Program.cs
  WebApi/Services/Auth/Models/TokenRequest.cs
  WebApi/Services/Auth/TokenService.cs
  WebApi/Services/Mail/MailService.cs
  WebApi/Services/VerifyCode/VerifyCodeService.cs
  WebApi/WebApi.csproj
Labels: enhancement

#11 Add prefix path api
  WebApi/Program.cs
  WebApi/WebApi.csproj
Labels: enhancement

#12 Update Dev
  WebApi/Program.cs
  WebApi/WebApi.csproj
Labels: dev update

#13 Migrate to Prod
  WebApi/Program.cs
  WebApi/WebApi.csproj
Labels: Migrate to prod

#15 Implement refresh token api
  WebApi/Features/Auth/Mappers/UserMapper.cs
  WebApi/Features/Auth/RefreshToken.cs
  WebApi/Services/Auth/TokenService.cs
Labels: enhancement

#18 Background task for user verify and Google Storage service
  WebApi/DependencyInjections/BackgroundServicesDI.cs
  WebApi/DependencyInjections/ServicesDI.cs
  WebApi/Program.cs
  WebApi/Services/Background/UserVerifyBG/UserVerifyStatusCheckService.cs
  WebApi/Services/Storage/GoogleStorageService.cs
Labels: enhancement

#20 Finish RolesFilter and JwtValidationFilter
  WebApi/Common/Exceptions/TechGadgetExceptionHandler.cs
  WebApi/Common/Filters/JwtValidationFilter.cs
  WebApi/Common/Filters/RequestValidationFilter.cs
  WebApi/Common/Filters/RolesFilter.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Specification/CreateSpecificationUnit.cs
  WebApi/Features/Users/GetCurrentUser.cs
  WebApi/Services/Auth/TokenService.cs
Labels: enhancement

#21 Update Dev
  WebApi/Common/Exceptions/TechGadgetExceptionHandler.cs
  WebApi/Common/Filters/JwtValidationFilter.cs
  WebApi/Common/Filters/RequestValidationFilter.cs
  WebApi/Common/Filters/RolesFilter.cs
  WebApi/Common/Utils/UtilityExtensions.cs
  WebApi/Common/Utils/VnPay/VnPayLibrary.cs
  WebApi/DependencyInjections/BackgroundServicesDI.cs
  WebApi/DependencyInjections/ServicesDI.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Specification/CreateSpecificationUnit.cs
  WebApi/Features/Users/GetCurrentUser.cs
  WebApi/Program.cs
  WebApi/Services/Auth/TokenService.cs
  WebApi/Services/Background/UserVerifyBG/UserVerifyStatusCheckService.cs
  WebApi/Services/Payment/Models/MomoPayment.cs
  WebApi/Services/Payment/Models/MomoPaymentRequest.cs
  WebApi/Services/Payment/Models/MomoPaymentResponse.cs
  WebApi/Services/Payment/Models/VnPayPayment.cs
  WebApi/Services/Payment/MomoPaymentService.cs
  WebApi/Services/Payment/VnPayPaymentService.cs
  WebApi/Services/Storage/GoogleStorageService.cs
Labels: dev update

#23 Finish CreateSpecificationUnit
  WebApi/Features/Specification/CreateSpecificationUnit.cs
  WebApi/Features/Specification/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/Specification/Models/SpecificationUnitResponse.cs
Labels: enhancement

#24 Update Dev
  WebApi/Features/Specification/CreateSpecificationUnit.cs
  WebApi/Features/Specification/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/Specification/Models/SpecificationUnitResponse.cs
Labels: dev update

#22 Update Prod
  WebApi/Common/Exceptions/TechGadgetExceptionHandler.cs
  WebApi/Common/Filters/JwtValidationFilter.cs
  WebApi/Common/Filters/RequestValidationFilter.cs
  WebApi/Common/Filters/RolesFilter.cs
  WebApi/Common/Utils/UtilityExtensions.cs
  WebApi/Common/Utils/VnPay/VnPayLibrary.cs
  WebApi/DependencyInjections/BackgroundServicesDI.cs
  WebApi/DependencyInjections/ServicesDI.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Specification/CreateSpecificationUnit.cs
  WebApi/Features/Specification/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/Specification/Models/SpecificationUnitResponse.cs
  WebApi/Features/Users/GetCurrentUser.cs
  WebApi/Program.cs
  WebApi/Services/Auth/TokenService.cs
  WebApi/Services/Background/UserVerifyBG/UserVerifyStatusCheckService.cs
  WebApi/Services/Payment/Models/MomoPayment.cs
  WebApi/Services/Payment/Models/MomoPaymentRequest.cs
  WebApi/Services/Payment/Models/MomoPaymentResponse.cs
  WebApi/Services/Payment/Models/VnPayPayment.cs
  WebApi/Services/Payment/MomoPaymentService.cs
  WebApi/Services/Payment/VnPayPaymentService.cs
  WebApi/Services/Storage/GoogleStorageService.cs
Labels: Migrate to prod

#25 Finish GetSpecificationUnitDetail
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Features/SpecificationUnits/CreateSpecificationUnit.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnitDetail.cs
  WebApi/Features/SpecificationUnits/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/SpecificationUnits/Models/SpecificationUnitResponse.cs
Labels: enhancement

#26 Create brand
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Common/Filters/RolesFilter.cs
  WebApi/Common/Paginations/PaginationResponse.cs
  WebApi/DependencyInjections/BackgroundServicesDI.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/ResendVerify.cs
  WebApi/Features/Auth/SignupUser.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Brands/CreateBrand.cs
  WebApi/Features/Brands/Mapper/BrandMapper.cs
  WebApi/Features/Brands/Models/BrandResponse.cs
  WebApi/Features/Specification/CreateSpecificationUnit.cs
  WebApi/Services/Background/UserVerifies/UserVerifyStatusCheckService.cs
  WebApi/Services/VerifyCode/VerifyCodeService.cs
Labels: enhancement

#27 Fix error code
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Common/Exceptions/TechGadgetException.cs
  WebApi/Common/Filters/JwtValidationFilter.cs
  WebApi/Common/Filters/RequestValidationFilter.cs
  WebApi/Common/Filters/RolesFilter.cs
  WebApi/Common/Paginations/PaginationResponse.cs
  WebApi/Features/Auth/GoogleLogin.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/ResendVerify.cs
  WebApi/Features/Auth/SignupUser.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Brands/CreateBrand.cs
  WebApi/Features/Specification/CreateSpecificationUnit.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnitDetail.cs
  WebApi/Services/Auth/CurrentUserService.cs
  WebApi/Services/Auth/TokenService.cs
  WebApi/Services/VerifyCode/VerifyCodeService.cs
Labels: bug

#28 Fix current server service
  WebApi/DependencyInjections/ServicesDI.cs
Labels: bug

#29 Update Dev
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Common/Exceptions/TechGadgetException.cs
  WebApi/Common/Filters/JwtValidationFilter.cs
  WebApi/Common/Filters/RequestValidationFilter.cs
  WebApi/Common/Filters/RolesFilter.cs
  WebApi/Common/Paginations/PaginationResponse.cs
  WebApi/DependencyInjections/BackgroundServicesDI.cs
  WebApi/DependencyInjections/ServicesDI.cs
  WebApi/Features/Auth/GoogleLogin.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/ResendVerify.cs
  WebApi/Features/Auth/SignupUser.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Brands/CreateBrand.cs
  WebApi/Features/Brands/Mapper/BrandMapper.cs
  WebApi/Features/Brands/Models/BrandResponse.cs
  WebApi/Features/SpecificationUnits/CreateSpecificationUnit.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnitDetail.cs
  WebApi/Features/SpecificationUnits/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/SpecificationUnits/Models/SpecificationUnitResponse.cs
  WebApi/Services/Auth/CurrentUserService.cs
  WebApi/Services/Auth/TokenService.cs
  WebApi/Services/Background/UserVerifies/UserVerifyStatusCheckService.cs
  WebApi/Services/VerifyCode/VerifyCodeService.cs
Labels: dev update

#30 Finish GetSpecificationUnits API
  WebApi/Features/SpecificationUnits/GetSpecificationUnitDetail.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnits.cs
  WebApi/Features/SpecificationUnits/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/SpecificationUnits/Models/SpecificationUnitsResponse.cs
Labels: enhancement

#31 Finish DeleteSpecificationUnitById and fix some error
  WebApi/Features/SpecificationUnits/CreateSpecificationUnit.cs
  WebApi/Features/SpecificationUnits/DeleteSpecificationUnitById.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnitDetail.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnits.cs
Labels: enhancement

#32 Update Dev
  WebApi/Features/SpecificationUnits/CreateSpecificationUnit.cs
  WebApi/Features/SpecificationUnits/DeleteSpecificationUnitById.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnitDetail.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnits.cs
  WebApi/Features/SpecificationUnits/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/SpecificationUnits/Models/SpecificationUnitsResponse.cs
Labels: dev update

#33 Update Prod
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Common/Exceptions/TechGadgetException.cs
  WebApi/Common/Filters/JwtValidationFilter.cs
  WebApi/Common/Filters/RequestValidationFilter.cs
  WebApi/Common/Filters/RolesFilter.cs
  WebApi/Common/Paginations/PaginationResponse.cs
  WebApi/DependencyInjections/BackgroundServicesDI.cs
  WebApi/DependencyInjections/ServicesDI.cs
  WebApi/Features/Auth/GoogleLogin.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/ResendVerify.cs
  WebApi/Features/Auth/SignupUser.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Brands/CreateBrand.cs
  WebApi/Features/Brands/Mapper/BrandMapper.cs
  WebApi/Features/Brands/Models/BrandResponse.cs
  WebApi/Features/Specification/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/SpecificationUnits/CreateSpecificationUnit.cs
  WebApi/Features/SpecificationUnits/DeleteSpecificationUnitById.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnitDetail.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnits.cs
  WebApi/Features/SpecificationUnits/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/SpecificationUnits/Models/SpecificationUnitResponse.cs
  WebApi/Features/SpecificationUnits/Models/SpecificationUnitsResponse.cs
  WebApi/Services/Auth/CurrentUserService.cs
  WebApi/Services/Auth/TokenService.cs
  WebApi/Services/Background/UserVerifies/UserVerifyStatusCheckService.cs
  WebApi/Services/VerifyCode/VerifyCodeService.cs
Labels: Migrate to prod

#38 Fix pagination
  WebApi/Common/Paginations/PaginationRequest.cs
  WebApi/Common/Paginations/PaginationResponse.cs
  WebApi/Features/Brands/GetBrands.cs
  WebApi/Features/Brands/Models/BrandsResponse.cs
  WebApi/Features/BusinessModels/GetBusinessModels.cs
  WebApi/Features/BusinessModels/Models/BusinessModelsResponse.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnits.cs
  WebApi/Features/SpecificationUnits/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/SpecificationUnits/Models/SpecificationUnitsResponse.cs
Labels: enhancement

#39 Update Dev
  WebApi/Common/Paginations/PaginationRequest.cs
  WebApi/Common/Paginations/PaginationResponse.cs
  WebApi/Features/Brands/GetBrands.cs
  WebApi/Features/Brands/Models/BrandsResponse.cs
  WebApi/Features/BusinessModels/GetBusinessModels.cs
  WebApi/Features/BusinessModels/Models/BusinessModelsResponse.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnits.cs
  WebApi/Features/SpecificationUnits/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/SpecificationUnits/Models/SpecificationUnitsResponse.cs
Labels: dev update

#40 Update Prod
  WebApi/Common/Paginations/PaginationRequest.cs
  WebApi/Common/Paginations/PaginationResponse.cs
  WebApi/Features/Brands/GetBrands.cs
  WebApi/Features/Brands/Models/BrandsResponse.cs
  WebApi/Features/BusinessModels/GetBusinessModels.cs
  WebApi/Features/BusinessModels/Models/BusinessModelsResponse.cs
  WebApi/Features/SpecificationUnits/GetSpecificationUnits.cs
  WebApi/Features/SpecificationUnits/Mappers/SpecificaitonUnitMapper.cs
  WebApi/Features/SpecificationUnits/Models/SpecificationUnitsResponse.cs
Labels: Migrate to prod
