Repository FA24SE112-Tech-Gadgets/TechGadgetsBackend, pull requests merged in 2024-11, with the labels that each got.

#187 Update Dev
  WebApi/Extensions/DbConnectionExtensions.cs
Labels: dev update

#188 Migrate to Prod
  WebApi/Extensions/DbConnectionExtensions.cs
Labels: prod migration

#189 fix socket unuse
  WebApi/Program.cs
Labels: enhancement

#192 Fix Auth API for sending deviceToken and add send notification for te…
  WebApi/Common/Settings/RabbitMQSettings.cs
  WebApi/Extensions/NotificationHubExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/Mappers/GoogleLoginMapper.cs
  WebApi/Features/Auth/Models/RegisterUserRequest.cs
  WebApi/Features/Auth/SignupUser.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Notifications/NotificationTestCurrent.cs
  WebApi/Features/Notifications/NotificationTestCurrentNew.cs
  WebApi/Services/Auth/CurrentUserService.cs
  WebApi/Services/Notification/RabbitMQService.cs
  WebApi/Services/Notifications/FCMNotificationService.cs
  WebApi/Services/Notifications/Models/TokenRequest.cs
  WebApi/Services/Notifications/NotificationService.cs
  WebApi/WebApi.csproj
Labels: enhancement

#193 Update Dev
  WebApi/Common/Settings/RabbitMQSettings.cs
  WebApi/Extensions/NotificationHubExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/Mappers/GoogleLoginMapper.cs
  WebApi/Features/Auth/Models/RegisterUserRequest.cs
  WebApi/Features/Auth/SignupUser.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Notifications/NotificationTestCurrent.cs
  WebApi/Features/Notifications/NotificationTestCurrentNew.cs
  WebApi/Services/Auth/CurrentUserService.cs
  WebApi/Services/Notification/RabbitMQService.cs
  WebApi/Services/Notifications/FCMNotificationService.cs
  WebApi/Services/Notifications/Models/TokenRequest.cs
  WebApi/Services/Notifications/NotificationService.cs
  WebApi/WebApi.csproj
Labels: dev update

#194 Migrate to prod
  WebApi/Common/Settings/RabbitMQSettings.cs
  WebApi/Extensions/NotificationHubExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/Mappers/GoogleLoginMapper.cs
  WebApi/Features/Auth/Models/RegisterUserRequest.cs
  WebApi/Features/Auth/SignupUser.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Notifications/NotificationTestCurrent.cs
  WebApi/Features/Notifications/NotificationTestCurrentNew.cs
  WebApi/Services/Auth/CurrentUserService.cs
  WebApi/Services/Notification/RabbitMQService.cs
  WebApi/Services/Notifications/FCMNotificationService.cs
  WebApi/Services/Notifications/Models/TokenRequest.cs
  WebApi/Services/Notifications/NotificationService.cs
  WebApi/WebApi.csproj
Labels: enhancement

#195 Apply notification
  WebApi/Common/Filters/Models/TokenRequest.cs
  WebApi/Common/Filters/RoleRestrictHubRequirement.cs
  WebApi/Extensions/NotificationHubExtensions.cs
  WebApi/Features/Notifications/GetNotificationsByCurrentUser.cs
  WebApi/Features/Notifications/Mappers/CustomerNotiMapper.cs
  WebApi/Features/Notifications/Mappers/NotificationMapper.cs
  WebApi/Features/Notifications/Mappers/SellerNotiMapper.cs
  WebApi/Features/Notifications/Models/CustomerNotiResponse.cs
  WebApi/Features/Notifications/Models/NotificationResponse.cs
  WebApi/Features/Notifications/Models/SellerNotiResponse.cs
  WebApi/Features/Notifications/Models/TokenRequest.cs
  WebApi/Features/Notifications/NotificationHub.cs
  WebApi/Features/Notifications/NotificationTestCurrent.cs
  WebApi/Features/Notifications/NotificationTestCurrentNew.cs
  WebApi/Features/Notifications/NotificationTestGroup.cs
  WebApi/Features/Notifications/UpdateNotificationIsRead.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/Program.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
  WebApi/Services/Background/WalletTrackings/ExpiredTransactionService.cs
  WebApi/Services/Notifications/Models/TokenRequest.cs
  WebApi/Services/Notifications/NotificationService.cs
  WebApi/appsettings.Local.json
Labels: enhancement

#198 Fix authentication problem and finish get list users, activate/deacti…
  WebApi/Data/Entities/Notification.cs
  WebApi/Features/Admins/UpdateAdminInfo.cs
  WebApi/Features/Auth/ForgotUserPassword.cs
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/RefreshToken.cs
  WebApi/Features/Auth/ResendVerify.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Carts/AddGadgetToCart.cs
  WebApi/Features/Carts/DeleteCartItemBySellerId.cs
  WebApi/Features/Carts/DeleteCustomerCartItems.cs
  WebApi/Features/Carts/RemoveGadgetOutOfCart.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/FavoriteGadgets/CustomerCreateDeleteFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/DeleteCustomerFavoriteGadgets.cs
  WebApi/Features/GadgetDiscounts/CreateGadgetDiscountByGadgetId.cs
  WebApi/Features/Gadgets/ActivateGadget.cs
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/DeactivateGadget.cs
  WebApi/Features/Gadgets/SetGadgetForSale.cs
  WebApi/Features/Gadgets/SetGadgetNotForSale.cs
  WebApi/Features/Managers/UpdateManagerInfo.cs
  WebApi/Features/Notifications/UpdateNotificationIsRead.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/UpdateReviewByReviewId.cs
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
  WebApi/Features/SellerApplications/RejectSellerApplication.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/SellerReplies/CreateSellerReply.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
  WebApi/Features/Sellers/UpdateSellerInfo.cs
  WebApi/Features/Users/ActivateUserByUserId.cs
  WebApi/Features/Users/ChangeUserPassword.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Features/Users/GetListUsers.cs
  WebApi/Features/WalletTrackings/CancelTransaction.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
Labels: enhancement

#199 Update Dev
  WebApi/Data/Entities/Notification.cs
  WebApi/Features/Admins/UpdateAdminInfo.cs
  WebApi/Features/Auth/ForgotUserPassword.cs
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/RefreshToken.cs
  WebApi/Features/Auth/ResendVerify.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Carts/AddGadgetToCart.cs
  WebApi/Features/Carts/DeleteCartItemBySellerId.cs
  WebApi/Features/Carts/DeleteCustomerCartItems.cs
  WebApi/Features/Carts/RemoveGadgetOutOfCart.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/FavoriteGadgets/CustomerCreateDeleteFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/DeleteCustomerFavoriteGadgets.cs
  WebApi/Features/GadgetDiscounts/CreateGadgetDiscountByGadgetId.cs
  WebApi/Features/Gadgets/ActivateGadget.cs
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/DeactivateGadget.cs
  WebApi/Features/Gadgets/SetGadgetForSale.cs
  WebApi/Features/Gadgets/SetGadgetNotForSale.cs
  WebApi/Features/Managers/UpdateManagerInfo.cs
  WebApi/Features/Notifications/UpdateNotificationIsRead.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/UpdateReviewByReviewId.cs
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
  WebApi/Features/SellerApplications/RejectSellerApplication.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/SellerReplies/CreateSellerReply.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
  WebApi/Features/Sellers/UpdateSellerInfo.cs
  WebApi/Features/Users/ActivateUserByUserId.cs
  WebApi/Features/Users/ChangeUserPassword.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Features/Users/GetListUsers.cs
  WebApi/Features/WalletTrackings/CancelTransaction.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
Labels: dev update

#200 Migrate to prod
  WebApi/Data/Entities/Notification.cs
  WebApi/Features/Admins/UpdateAdminInfo.cs
  WebApi/Features/Auth/ForgotUserPassword.cs
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Auth/RefreshToken.cs
  WebApi/Features/Auth/ResendVerify.cs
  WebApi/Features/Auth/VerifyUser.cs
  WebApi/Features/Carts/AddGadgetToCart.cs
  WebApi/Features/Carts/DeleteCartItemBySellerId.cs
  WebApi/Features/Carts/DeleteCustomerCartItems.cs
  WebApi/Features/Carts/RemoveGadgetOutOfCart.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/FavoriteGadgets/CustomerCreateDeleteFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/DeleteCustomerFavoriteGadgets.cs
  WebApi/Features/GadgetDiscounts/CreateGadgetDiscountByGadgetId.cs
  WebApi/Features/Gadgets/ActivateGadget.cs
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/DeactivateGadget.cs
  WebApi/Features/Gadgets/SetGadgetForSale.cs
  WebApi/Features/Gadgets/SetGadgetNotForSale.cs
  WebApi/Features/Managers/UpdateManagerInfo.cs
  WebApi/Features/Notifications/UpdateNotificationIsRead.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/UpdateReviewByReviewId.cs
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
  WebApi/Features/SellerApplications/CreateSellerApplication.cs
  WebApi/Features/SellerApplications/RejectSellerApplication.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/SellerReplies/CreateSellerReply.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
  WebApi/Features/Sellers/UpdateSellerInfo.cs
  WebApi/Features/Users/ActivateUserByUserId.cs
  WebApi/Features/Users/ChangeUserPassword.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Features/Users/GetListUsers.cs
  WebApi/Features/WalletTrackings/CancelTransaction.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
Labels: prod migration

#201 Finish api get wallet tracking by id and fix create wallet deposit fo…
  WebApi/Features/WalletTrackings/GetWalletTrackingById.cs
  WebApi/Features/WalletTrackings/Models/DepositResponse.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
Labels: enhancement

#202 Update Dev
  WebApi/Features/WalletTrackings/GetWalletTrackingById.cs
  WebApi/Features/WalletTrackings/Models/DepositResponse.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
Labels: dev update

#203 Migrate to prod
  WebApi/Features/WalletTrackings/GetWalletTrackingById.cs
  WebApi/Features/WalletTrackings/Models/DepositResponse.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
Labels: prod migration

#204 finish
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
Labels: enhancement

#205 Update Dev
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
Labels: dev update

#206 Migrate to prod
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
Labels: prod migration

#207 Fix gadgets
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetRelatedToSellerResponse.cs
Labels: enhancement

#208 Update Dev
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetRelatedToSellerResponse.cs
Labels: dev update

#209 Migrate to prod
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetRelatedToSellerResponse.cs
Labels: prod migration

#210 Gadget related to seller response
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetRelatedToSellerResponse.cs
Labels: enhancement

#211 Search with natural language
  WebApi/Common/Exceptions/TechGadgetExceptionHandler.cs
  WebApi/Common/Settings/OpenAIClientSettings.cs
  WebApi/Common/Utils/StringExtensions.cs
  WebApi/Data/Seeds/SpecificationValueDienThoaiSeed.cs
  WebApi/Data/Seeds/SpecificationValueLaptopSeed.cs
  WebApi/Extensions/ApplyMigrationsExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Features/FavoriteGadgets/GetCustomerFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/Mappers/FavoriteGadgetMapper.cs
  WebApi/Features/GadgetHistories/Mappers/GadgetHistoryMapper.cs
  WebApi/Features/Gadgets/GetGadgetByBrandId.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
  WebApi/Features/Gadgets/GetGadgetById.cs
  WebApi/Features/Gadgets/GetGadgets.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetResponse.cs
  WebApi/Features/NaturalLanguages/Models/ProcessNaturalLanguageResponse.cs
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Tests/CompareEmbedding.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
  WebApi/Services/Embedding/EmbeddingService.cs
  WebApi/Services/NaturalLanguage/Models/NaturalLanguageRequest.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
  WebApi/WebApi.csproj
  WebApi/appsettings.Local.json
Labels: enhancement

#212 Update Dev
  WebApi/Common/Exceptions/TechGadgetExceptionHandler.cs
  WebApi/Common/Settings/OpenAIClientSettings.cs
  WebApi/Common/Utils/StringExtensions.cs
  WebApi/Data/Seeds/SpecificationValueDienThoaiSeed.cs
  WebApi/Data/Seeds/SpecificationValueLaptopSeed.cs
  WebApi/Extensions/ApplyMigrationsExtensions.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Features/FavoriteGadgets/GetCustomerFavoriteGadget.cs
  WebApi/Features/FavoriteGadgets/Mappers/FavoriteGadgetMapper.cs
  WebApi/Features/GadgetHistories/Mappers/GadgetHistoryMapper.cs
  WebApi/Features/Gadgets/GetGadgetByBrandId.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
  WebApi/Features/Gadgets/GetGadgetById.cs
  WebApi/Features/Gadgets/GetGadgets.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetRelatedToSellerResponse.cs
  WebApi/Features/Gadgets/Models/GadgetResponse.cs
  WebApi/Features/NaturalLanguages/Models/ProcessNaturalLanguageResponse.cs
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Tests/CompareEmbedding.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
  WebApi/Services/Embedding/EmbeddingService.cs
  WebApi/Services/NaturalLanguage/Models/NaturalLanguageRequest.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
  WebApi/WebApi.csproj
  WebApi/appsettings.Local.json
Labels: dev update

#213 Fix OpenAI key
  WebApi/Common/Settings/AesEncryptionSettings.cs
  WebApi/Common/Settings/OpenAIClientSettings.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Services/Cryption/AesEncryptionService.cs
  WebApi/Services/Embedding/EmbeddingService.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
  WebApi/appsettings.Local.json
Labels: bug

#214 Update Dev
  WebApi/Common/Settings/AesEncryptionSettings.cs
  WebApi/Common/Settings/OpenAIClientSettings.cs
  WebApi/Extensions/ServicesExtensions.cs
  WebApi/Extensions/SettingsExtensions.cs
  WebApi/Services/Cryption/AesEncryptionService.cs
  WebApi/Services/Embedding/EmbeddingService.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
  WebApi/appsettings.Local.json
Labels: dev update

#215 Add Rate Limiter
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Extensions/RateLimiterExtensions.cs
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/GetSuggestedGadgetsByGadgetId.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Tests/CompareGadget.cs
  WebApi/Features/Tests/IsPositiveContent.cs
  WebApi/Features/Tests/TestEndpoint.cs
  WebApi/Program.cs
  WebApi/Services/NaturalLanguage/Models/IsPositiveRequest.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
Labels: enhancement

#216 Update Dev
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Extensions/RateLimiterExtensions.cs
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/GetSuggestedGadgetsByGadgetId.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Tests/CompareGadget.cs
  WebApi/Features/Tests/IsPositiveContent.cs
  WebApi/Features/Tests/TestEndpoint.cs
  WebApi/Program.cs
  WebApi/Services/NaturalLanguage/Models/IsPositiveRequest.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
Labels: dev update

#217 Migrate to Prod
  WebApi/Common/Exceptions/TechGadgetErrorCode.cs
  WebApi/Extensions/RateLimiterExtensions.cs
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/GetSuggestedGadgetsByGadgetId.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Tests/CompareGadget.cs
  WebApi/Features/Tests/IsPositiveContent.cs
  WebApi/Features/Tests/TestEndpoint.cs
  WebApi/Program.cs
  WebApi/Services/NaturalLanguage/Models/IsPositiveRequest.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
Labels: prod migration

#218 fix response
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
  WebApi/Features/SellerOrders/Models/SellerOrderResponse.cs
Labels: enhancement

#219 Update Dev
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
  WebApi/Features/SellerOrders/Models/SellerOrderResponse.cs
Labels: dev update

#220 update
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
Labels: enhancement

#221 Update Dev
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
Labels: dev update

#223 Update Dev
  WebApi/Features/SellerOrders/GetListSellerOrderItemsBySellerOrderId.cs
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
Labels: dev update

#224 Migrate to prod
  WebApi/Features/SellerOrders/GetListSellerOrderItemsBySellerOrderId.cs
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
  WebApi/Features/SellerOrders/Models/SellerOrderResponse.cs
Labels: prod migration

#225 fix bug
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
Labels: bug

#226 MIgrate to prod
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
Labels: prod migration

#227 Get Suggested Gadgets For Current Customer
  WebApi/Features/Gadgets/GetSuggestedGadgetsForCurrentCustomer.cs
Labels: dev update

#228 Update Dev
  WebApi/Features/Gadgets/GetSuggestedGadgetsForCurrentCustomer.cs
Labels: dev update

#229 Migrate to Prod
  WebApi/Features/Gadgets/GetSuggestedGadgetsForCurrentCustomer.cs
Labels: prod migration

#230 Fix seller reply url
  WebApi/Features/SellerReplies/CreateSellerReply.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
Labels: bug

#231 Update Dev
  WebApi/Features/SellerReplies/CreateSellerReply.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
Labels: dev update

#232 Migrate to prod
  WebApi/Features/SellerReplies/CreateSellerReply.cs
  WebApi/Features/SellerReplies/UpdateSellerReplyById.cs
Labels: prod migration

#233 Seller Update Gadget
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetDetailResponse.cs
  WebApi/Features/Gadgets/Models/GadgetImageResponse.cs
  WebApi/Features/Gadgets/SetGadgetForSale.cs
  WebApi/Features/Gadgets/UpdateGadget.cs
  WebApi/Services/Auth/CurrentUserService.cs
Labels: enhancement

#234 Update Dev
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetDetailResponse.cs
  WebApi/Features/Gadgets/Models/GadgetImageResponse.cs
  WebApi/Features/Gadgets/SetGadgetForSale.cs
  WebApi/Features/Gadgets/UpdateGadget.cs
  WebApi/Services/Auth/CurrentUserService.cs
Labels: dev update

#235 Modify Update Gadget description
  WebApi/Features/Gadgets/UpdateGadget.cs
Labels: enhancement

#236 Update Dev
  WebApi/Features/Gadgets/UpdateGadget.cs
Labels: dev update

#237 Migrate to Prod
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/GadgetDetailResponse.cs
  WebApi/Features/Gadgets/Models/GadgetImageResponse.cs
  WebApi/Features/Gadgets/SetGadgetForSale.cs
  WebApi/Features/Gadgets/UpdateGadget.cs
  WebApi/Services/Auth/CurrentUserService.cs
Labels: prod migration

#238 Get summary review
  WebApi/Features/Carts/AddGadgetToCart.cs
  WebApi/Features/Carts/DeleteCustomerCartItems.cs
  WebApi/Features/Carts/GetCartItemsBySellerId.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/GadgetDiscounts/CreateGadgetDiscountByGadgetId.cs
  WebApi/Features/Gadgets/UpdateGadget.cs
  WebApi/Features/Managers/UpdateManagerInfo.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/GetGadgetsReviews.cs
  WebApi/Features/Reviews/GetReviewSummaryByGadgetId.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
  WebApi/Features/Reviews/Mappers/ReviewMapper.cs
  WebApi/Features/Reviews/Models/ReviewResponse.cs
  WebApi/Features/Reviews/Models/ReviewSummaryResponse.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
Labels: enhancement

#239 Update Dev
  WebApi/Features/Carts/AddGadgetToCart.cs
  WebApi/Features/Carts/DeleteCustomerCartItems.cs
  WebApi/Features/Carts/GetCartItemsBySellerId.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/GadgetDiscounts/CreateGadgetDiscountByGadgetId.cs
  WebApi/Features/Gadgets/UpdateGadget.cs
  WebApi/Features/Managers/UpdateManagerInfo.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/GetGadgetsReviews.cs
  WebApi/Features/Reviews/GetReviewSummaryByGadgetId.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
  WebApi/Features/Reviews/Mappers/ReviewMapper.cs
  WebApi/Features/Reviews/Models/ReviewResponse.cs
  WebApi/Features/Reviews/Models/ReviewSummaryResponse.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
Labels: dev update

#241 Fix Get Summary
  WebApi/Features/Reviews/GetReviewSummaryByGadgetId.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
Labels: bug

#242 Update Dev
  WebApi/Features/Reviews/GetReviewSummaryByGadgetId.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
Labels: dev update

#243 Migrate to Prod
  WebApi/Features/Reviews/GetReviewSummaryByGadgetId.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
Labels: prod migration

#244 fix send device token
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
Labels: enhancement

#245 Update Dev
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
Labels: dev update

#246 Migrate to prod
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
Labels: prod migration

#247 Update all notification isRead to true
  WebApi/Features/Notifications/UpdateAllNotificationIsRead.cs
Labels: enhancement

#248 Add SellerOrderId to WalletTrackingReponse
  WebApi/Features/WalletTrackings/Mappers/WalletTrackingMapper.cs
  WebApi/Features/WalletTrackings/Models/DepositResponse.cs
  WebApi/Features/WalletTrackings/Models/WalletTrackingItemResponse.cs
Labels: enhancement

#249 Update Dev
  WebApi/Features/Notifications/UpdateAllNotificationIsRead.cs
  WebApi/Features/WalletTrackings/Mappers/WalletTrackingMapper.cs
  WebApi/Features/WalletTrackings/Models/DepositResponse.cs
  WebApi/Features/WalletTrackings/Models/WalletTrackingItemResponse.cs
Labels: dev update

#250 Migrate to Prod
  WebApi/Features/Notifications/UpdateAllNotificationIsRead.cs
  WebApi/Features/WalletTrackings/Mappers/WalletTrackingMapper.cs
  WebApi/Features/WalletTrackings/Models/DepositResponse.cs
  WebApi/Features/WalletTrackings/Models/WalletTrackingItemResponse.cs
Labels: prod migration

#251 Fix ConfirmSellerOrder Notification
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
Labels: bug

#252 Update Dev
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
Labels: dev update

#253 Migrate to Prod
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
Labels: prod migration

#254 Add WalletTrackingId to Notification
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
  WebApi/Services/NaturalLanguage/Models/NaturalLanguageRequest.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
Labels: enhancement

#255 Update Dev
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
  WebApi/Services/NaturalLanguage/Models/NaturalLanguageRequest.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
Labels: dev update

#256 Migrate to Prod
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
  WebApi/Services/NaturalLanguage/Models/NaturalLanguageRequest.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
Labels: prod migration

#257 Fix IsFavorite in Search with Natural Language
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
Labels: bug

#261 Fix API Get reviews/seller-order-items
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/GetGadgetsReviews.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
Labels: bug

#263 Fix Create Review Rating from 1 to 5
  WebApi/Features/Reviews/CreateReview.cs
Labels: bug

#264 Fix Update Vector when Update Gadget
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Features/Gadgets/UpdateGadget.cs
  WebApi/Services/Background/GadgetDiscounts/InactiveGadgetDiscountService.cs
Labels: bug

#265 Update Dev
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Features/Gadgets/UpdateGadget.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Services/Background/GadgetDiscounts/InactiveGadgetDiscountService.cs
Labels: dev update

#266 Migrate to Prod
  WebApi/Extensions/BackgroundServicesExtensions.cs
  WebApi/Features/Gadgets/UpdateGadget.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Services/Background/GadgetDiscounts/InactiveGadgetDiscountService.cs
Labels: prod migration

#267 Create notification for sellers when create order
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/Users/ActivateUserByUserId.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
  WebApi/Services/Background/WalletTrackings/ExpiredTransactionService.cs
Labels: enhancement

#268 Update Dev
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/Users/ActivateUserByUserId.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
  WebApi/Services/Background/WalletTrackings/ExpiredTransactionService.cs
Labels: dev update

#269 Migrate to Prod
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/Users/ActivateUserByUserId.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
  WebApi/Services/Background/WalletTrackings/ExpiredTransactionService.cs
Labels: prod migration

#270 Fix cancel seller order notification
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
Labels: bug

#271 Update Dev
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
Labels: dev update

#272 Migrate to Prod
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
Labels: prod migration

#273 Delete Device Token
  WebApi/Features/DeviceToken/DeleteDeviceToken.cs
Labels: enhancement

#274 Add UserId to FCM Notification
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
  WebApi/Services/Background/WalletTrackings/ExpiredTransactionService.cs
Labels: enhancement

#276 Migrate to Prod
  WebApi/Features/Customers/UpdateCustomerInfo.cs
  WebApi/Features/DeviceToken/DeleteDeviceToken.cs
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/Models/HotGadgetResponse.cs
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Features/Wallets/CreateWalletDeposit.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
  WebApi/Services/Background/WalletTrackings/ExpiredTransactionService.cs
Labels: prod migration

#277 Fix Update Seller,Customer Information
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
Labels: bug

#278 Migrate to Prod
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/SellerApplications/ApproveSellerApplication.cs
Labels: prod migration

#279 Update Dev
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/HotGadgetResponse.cs
Labels: dev update

#280 Migrate to Prod
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/HotGadgetResponse.cs
Labels: prod migration

#283 Update Dev
  WebApi/Features/Gadgets/GetGadgetByBrandId.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdForManager.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
Labels: dev update

#284 Migrate to Prod
  WebApi/Features/Gadgets/GetGadgetByBrandId.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdForManager.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
Labels: prod migration

#285 Update Dev
  WebApi/Features/Gadgets/DeactivateGadget.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/SpecificationKeyResponse.cs
  WebApi/Features/Gadgets/Models/SpecificationUnitResponse.cs
  WebApi/Features/Gadgets/Models/SpecificationValueResponse.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/GetGadgetsReviews.cs
  WebApi/Features/Reviews/Models/GadgetReviewResponse.cs
  WebApi/Features/SellerOrders/GetListSellerOrderItemsBySellerOrderId.cs
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
  WebApi/Features/SellerOrders/Models/SellerOrderItemInItemResponse.cs
  WebApi/Features/SellerReplies/CreateSellerReply.cs
Labels: dev update

#286 Migrate to Prod
  WebApi/Features/Gadgets/DeactivateGadget.cs
  WebApi/Features/Gadgets/Mappers/GadgetMapper.cs
  WebApi/Features/Gadgets/Models/SpecificationKeyResponse.cs
  WebApi/Features/Gadgets/Models/SpecificationUnitResponse.cs
  WebApi/Features/Gadgets/Models/SpecificationValueResponse.cs
  WebApi/Features/Reviews/CreateReview.cs
  WebApi/Features/Reviews/GetGadgetsReviews.cs
  WebApi/Features/Reviews/Models/GadgetReviewResponse.cs
  WebApi/Features/SellerOrders/GetListSellerOrderItemsBySellerOrderId.cs
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
  WebApi/Features/SellerOrders/Models/SellerOrderItemInItemResponse.cs
  WebApi/Features/SellerReplies/CreateSellerReply.cs
Labels: prod migration

#287 Update Dev
  WebApi/Features/Users/Models/SellerResponse.cs
Labels: dev update

#288 Migrate to Prod
  WebApi/Features/Users/Models/SellerResponse.cs
Labels: prod migration

#293 Update Dev
  WebApi/Features/GadgetDiscounts/CancelGadgetDiscountByGadgetId.cs
Labels: dev update

#294 Migrate to Prod
  WebApi/Features/GadgetDiscounts/CancelGadgetDiscountByGadgetId.cs
Labels: prod migration

#296 Migrate to Prod
  WebApi/Features/Brands/CreateBrand.cs
  WebApi/Features/Brands/DeleteBrand.cs
  WebApi/Features/Categories/CreateCategory.cs
  WebApi/Features/Categories/DeleteCategory.cs
  WebApi/Features/Gadgets/DeleteGadget.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdForManager.cs
Labels: prod migration

#298 Migrate to Prod
  WebApi/Features/Auth/Mappers/UserMapper.cs
  WebApi/Features/SpecificationKeys/CreateSpecificationKey.cs
  WebApi/Features/SpecificationKeys/DeleteSpecificationKey.cs
  WebApi/Features/SpecificationUnits/CreateSpecificationUnit.cs
  WebApi/Features/SpecificationUnits/DeleteSpecificationUnit.cs
Labels: prod migration

#299 Update Dev
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
Labels: dev update

#300 Migrate to Prod
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
Labels: prod migration

#301 Update Dev
  WebApi/Common/Paginations/QueryExtension.cs
  WebApi/Features/Gadgets/GetGadgetByBrandId.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
  WebApi/Features/Gadgets/GetGadgets.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/GetSuggestedGadgetsByGadgetId.cs
  WebApi/Features/Gadgets/GetSuggestedGadgetsForCurrentCustomer.cs
  WebApi/Features/Reviews/GetGadgetsReviews.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
  WebApi/Features/Reviews/GetReviewsHomePage.cs
  WebApi/Features/Tests/TestEndpoint.cs
Labels: dev update

#302 Migrate to Prod
  WebApi/Common/Paginations/QueryExtension.cs
  WebApi/Features/Gadgets/GetGadgetByBrandId.cs
  WebApi/Features/Gadgets/GetGadgetByCategoryId.cs
  WebApi/Features/Gadgets/GetGadgets.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdWithFilter.cs
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
  WebApi/Features/Gadgets/GetHotGadgets.cs
  WebApi/Features/Gadgets/GetSuggestedGadgetsByGadgetId.cs
  WebApi/Features/Gadgets/GetSuggestedGadgetsForCurrentCustomer.cs
  WebApi/Features/Reviews/GetGadgetsReviews.cs
  WebApi/Features/Reviews/GetReviewsByGadgetId.cs
  WebApi/Features/Reviews/GetReviewsHomePage.cs
  WebApi/Features/Tests/TestEndpoint.cs
Labels: prod migration

#303 Update Dev
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Reviews/GetReviewsHomePage.cs
  WebApi/Features/Tests/TestEndpoint.cs
Labels: dev update

#304 Migrate to Prod
  WebApi/Features/Gadgets/CreateGadget.cs
  WebApi/Features/Reviews/GetReviewsHomePage.cs
  WebApi/Features/Tests/TestEndpoint.cs
Labels: prod migration

#305 Update Dev
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/Stats/GetNumberOfGadgetsByManager.cs
  WebApi/Features/Stats/GetNumberOfGadgetsBySeller.cs
  WebApi/Features/Stats/GetNumberOfSellerOrdersByManager.cs
  WebApi/Features/Stats/GetNumberOfSellerOrdersBySeller.cs
  WebApi/Features/Stats/GetNumberOfSoldGadgetsByManager.cs
  WebApi/Features/Stats/GetNumberOfSoldGadgetsBySeller.cs
  WebApi/Features/Stats/GetSalesRevenueByManager.cs
  WebApi/Features/Stats/GetSalesRevenueBySeller.cs
  WebApi/Features/Tests/TestEndpoint.cs
Labels: dev update

#306 Migrate to Prod
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/Stats/GetNumberOfGadgetsByManager.cs
  WebApi/Features/Stats/GetNumberOfGadgetsBySeller.cs
  WebApi/Features/Stats/GetNumberOfSellerOrdersByManager.cs
  WebApi/Features/Stats/GetNumberOfSellerOrdersBySeller.cs
  WebApi/Features/Stats/GetNumberOfSoldGadgetsByManager.cs
  WebApi/Features/Stats/GetNumberOfSoldGadgetsBySeller.cs
  WebApi/Features/Stats/GetSalesRevenueByManager.cs
  WebApi/Features/Stats/GetSalesRevenueBySeller.cs
  WebApi/Features/Tests/TestEndpoint.cs
Labels: prod migration

#307 Update Dev
  WebApi/Features/Stats/GetNumberOfSellerOrdersByManager.cs
  WebApi/Features/Stats/GetNumberOfSellerOrdersBySeller.cs
  WebApi/Features/Stats/GetSalesRevenueByManager.cs
  WebApi/Features/Stats/GetSalesRevenueBySeller.cs
Labels: dev update

#308 Migrate to Prod
  WebApi/Features/Stats/GetNumberOfSellerOrdersByManager.cs
  WebApi/Features/Stats/GetNumberOfSellerOrdersBySeller.cs
  WebApi/Features/Stats/GetSalesRevenueByManager.cs
  WebApi/Features/Stats/GetSalesRevenueBySeller.cs
Labels: prod migration

#311 Update Dev
  WebApi/Features/Reviews/ActivateReviewByManager.cs
  WebApi/Features/Reviews/DeactivateReviewByManager.cs
  WebApi/Features/SellerReplies/ActivateSellerReplyByManager.cs
  WebApi/Features/SellerReplies/DeactivateSellerReplyByManager.cs
Labels: dev update

#312 Migrate to Prod
  WebApi/Features/Reviews/ActivateReviewByManager.cs
  WebApi/Features/Reviews/DeactivateReviewByManager.cs
  WebApi/Features/SellerReplies/ActivateSellerReplyByManager.cs
  WebApi/Features/SellerReplies/DeactivateSellerReplyByManager.cs
Labels: prod migration

#317 Update Dev
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
Labels: dev update

#318 Migrate to Prod
  WebApi/Features/SellerOrders/GetListSellerOrders.cs
  WebApi/Features/SellerOrders/Mappers/SellerOrderMapper.cs
Labels: prod migration

#319 Update Dev
  WebApi/Features/Gadgets/GetGadgets.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdForManager.cs
  WebApi/Features/Gadgets/GetGadgetsByCurrentSeller.cs
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Stats/GetNumberOfSellerOrdersByManager.cs
  WebApi/Features/Stats/GetNumberOfSellerOrdersBySeller.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
Labels: dev update

#320 Migrate to Prod
  WebApi/Features/Gadgets/GetGadgets.cs
  WebApi/Features/Gadgets/GetGadgetsByCategoryIdForManager.cs
  WebApi/Features/Gadgets/GetGadgetsByCurrentSeller.cs
  WebApi/Features/Gadgets/GetGadgetsBySeller.cs
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Stats/GetNumberOfSellerOrdersByManager.cs
  WebApi/Features/Stats/GetNumberOfSellerOrdersBySeller.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
Labels: prod migration

#321 Update Dev
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
Labels: dev update

#322 Migrate to Prod
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
Labels: prod migration

#323 Update Dev
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
Labels: dev update

#324 Migrate to Prod
  WebApi/Features/NaturalLanguages/ProcessNaturalLanguage.cs
  WebApi/Features/Tests/ProcessNaturalLanuage.cs
Labels: prod migration

#325 Update Dev
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
Labels: dev update

#326 Migrate to Prod
  WebApi/Services/NaturalLanguage/NaturalLanguageService.cs
Labels: prod migration

#331 Update Dev
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
Labels: dev update

#332 Migrate to Prod
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
  WebApi/Services/Background/SellerOrders/SellerOrderService.cs
Labels: prod migration

#333 Update Dev
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/SellerOrders/GetSellerOrderById.cs
  WebApi/Features/SellerOrders/Models/SellerInSellerOrderResponse.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
Labels: dev update

#334 Migrate to Prod
  WebApi/Features/Orders/CreateOrder.cs
  WebApi/Features/Orders/CreateOrderNow.cs
  WebApi/Features/SellerOrders/CancelSellerOrder.cs
  WebApi/Features/SellerOrders/ConfirmSellerOrder.cs
  WebApi/Features/SellerOrders/GetSellerOrderById.cs
  WebApi/Features/SellerOrders/Models/SellerInSellerOrderResponse.cs
  WebApi/Features/Users/DeactivateUserByUserId.cs
Labels: prod migration

#335 Update Dev
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Carts/AddGadgetToCart.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/GadgetDiscounts/CancelGadgetDiscountByGadgetId.cs
  WebApi/Features/GadgetDiscounts/CreateGadgetDiscountByGadgetId.cs
  WebApi/Features/GadgetHistories/GetGadgetHistories.cs
  WebApi/Features/Gadgets/DeactivateGadget.cs
  WebApi/Features/Gadgets/GetGadgetById.cs
  WebApi/Features/Gadgets/SetGadgetForSale.cs
  WebApi/Features/Gadgets/SetGadgetNotForSale.cs
  WebApi/Features/KeywordHistories/DeleteAllKeywordHistory.cs
  WebApi/Features/KeywordHistories/DeleteKeywordHistoryById.cs
  WebApi/Features/Sellers/GetSeller.cs
  WebApi/Features/Sellers/Mappers/SellerMapper.cs
  WebApi/Features/Sellers/Models/SellerResponse.cs
  WebApi/Features/Users/GetListUsers.cs
Labels: dev update

#336 Migrate to Prod
  WebApi/Features/Auth/LoginGoogle.cs
  WebApi/Features/Auth/LoginUser.cs
  WebApi/Features/Carts/AddGadgetToCart.cs
  WebApi/Features/Carts/UpdateCartItem.cs
  WebApi/Features/GadgetDiscounts/CancelGadgetDiscountByGadgetId.cs
  WebApi/Features/GadgetDiscounts/CreateGadgetDiscountByGadgetId.cs
  WebApi/Features/GadgetHistories/GetGadgetHistories.cs
  WebApi/Features/Gadgets/DeactivateGadget.cs
  WebApi/Features/Gadgets/GetGadgetById.cs
  WebApi/Features/Gadgets/SetGadgetForSale.cs
  WebApi/Features/Gadgets/SetGadgetNotForSale.cs
  WebApi/Features/KeywordHistories/DeleteAllKeywordHistory.cs
  WebApi/Features/KeywordHistories/DeleteKeywordHistoryById.cs
  WebApi/Features/Sellers/GetSeller.cs
  WebApi/Features/Sellers/Mappers/SellerMapper.cs
  WebApi/Features/Sellers/Models/SellerResponse.cs
  WebApi/Features/Users/GetListUsers.cs
Labels: prod migration
